language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

matrix:
  include:
    - if: branch = master
      env: TOXFACTOR=master
      after_success: codecov
    - if: branch != master
      env: TOXFACTOR=dev
      after_success: codecov
    - env: TOXENV=build
      python: 2.7
    - env: TOXENV=pre-commit
      python: 3.7
      dist: xenial

install:
  - pip install tox-factor
  - pip install codecov

script: tox
