language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt --extra-index-url https://testpypi.python.org/pypi
    - pip install -r test_requirements.txt --extra-index-url https://testpypi.python.org/pypi
    - pip install coveralls

script:
    - python runtests.py --with-coverage  

after_success:
    coveralls
    
